CREATE TABLE ai_phase3_event (
    id BIGINT NOT NULL AUTO_INCREMENT,
    event_key VARCHAR(200) NOT NULL,
    source_id VARCHAR(100) NOT NULL,
    session_id VARCHAR(36) NOT NULL,
    source_type VARCHAR(30) NOT NULL,
    drone_id BIGINT NOT NULL,
    track_id BIGINT NOT NULL,
    frame_index BIGINT NOT NULL,
    captured_at DATETIME(6) NOT NULL,
    ppe_state VARCHAR(40) NOT NULL,
    no_helmet_rate DECIMAL(8, 6) NOT NULL,
    helmet_rate DECIMAL(8, 6) NOT NULL,
    unknown_rate DECIMAL(8, 6) NOT NULL,
    streak_seconds DECIMAL(12, 3) NOT NULL,
    estimated_depth_m DECIMAL(12, 3) NULL,
    scene_q33_m DECIMAL(12, 3) NULL,
    scene_q66_m DECIMAL(12, 3) NULL,
    depth_bucket VARCHAR(20) NULL,
    enrichment_latency_ms DECIMAL(12, 2) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,

    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_phase3_event_key (event_key),
    KEY idx_ai_phase3_drone_captured (drone_id, captured_at),
    KEY idx_ai_phase3_session_captured (session_id, captured_at),

    CONSTRAINT chk_ai_phase3_frame_index CHECK (frame_index >= 0),
    CONSTRAINT chk_ai_phase3_track_id CHECK (track_id > 0),
    CONSTRAINT chk_ai_phase3_no_helmet_rate CHECK (no_helmet_rate >= 0 AND no_helmet_rate <= 1),
    CONSTRAINT chk_ai_phase3_helmet_rate CHECK (helmet_rate >= 0 AND helmet_rate <= 1),
    CONSTRAINT chk_ai_phase3_unknown_rate CHECK (unknown_rate >= 0 AND unknown_rate <= 1),
    CONSTRAINT chk_ai_phase3_streak CHECK (streak_seconds >= 0),
    CONSTRAINT chk_ai_phase3_depth_bucket CHECK (depth_bucket IS NULL OR depth_bucket IN ('NEAR', 'MID', 'FAR', 'UNKNOWN'))
);
